[env]
TERM = "xterm-256color"

[window]
decorations = "none"
dynamic_padding = false
opacity = 1.0
startup_mode = "Maximized"

[terminal.shell]
program = "/usr/bin/tmux"

[mouse]
hide_when_typing = true

[font]
size = 12.0

[font.bold]
family = "AdwaitaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "AdwaitaMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "AdwaitaMono Nerd Font"
style = "Italic"

[font.normal]
family = "AdwaitaMono Nerd Font"
style = "Regular"

[colors.primary]
background = "#1e2326"
foreground = "#d3c6aa"
dim_foreground = "#9E9580"
bright_foreground = "#B3A891"

[colors.cursor]
text = "#1e2326"
cursor = "#d3c6aa"

[colors.vi_mode_cursor]
text = "#1e2326"
cursor = "#d699b6"

[colors.search.matches]
foreground = "#1e2326"
background = "#e69875"

[colors.search.focused_match]
foreground = "#1e2326"
background = "#a7c080"

[colors.footer_bar]
foreground = "#121517"
background = "#B3A891"

[colors.hints.start]
foreground = "#262c30"
background = "#4a545a"

[colors.hints.end]
foreground = "#1B2022"
background = "#5d6970"

[colors.selection]
text = "#262c30"
background = "#9E9580"

[colors.normal]
black = "#262c30"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#7fbbb3"
white = "#5d6970"

[colors.bright]
black = "#384044"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#7fbbb3"
white = "#4a545a"

[[colors.indexed_colors]]
index = 16
color = "#e69875"

[[colors.indexed_colors]]
index = 17
color = "#B3A891"
